# Generated by Django 3.1.7 on 2021-03-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_payed',
            new_name='is_paid',
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
