# Generated by Django 3.1.7 on 2021-03-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_auto_20210326_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullname',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
