# Generated by Django 3.1.7 on 2021-03-26 05:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0005_auto_20210326_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_produced',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(1000000000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facility',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='passport',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(verbose_name=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000000000), django.core.validators.MinValueValidator(0)])),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepay_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
